import requests
import time
import random

# Your Discord account token
TOKEN = 'DISCORD_TOKEN'

# The ID of the channel you want to send messages to
CHANNEL_ID = 'CHANNEL ID'

# A list of messages to send
MESSAGES = [
        "What's your favorite book",
		"Have you tried this recipe",
		"I can't stop listening to this song!",
		"Do you have any weekend plans",
		"Where did you get that jacket",
		"I'm learning to play the guitar.",
		"Have you been to this new caf'",
		"Your haircut looks great!",
		"I just started a new hobby!",
		"Have you seen this funny video",
		"What's your favorite vacation spot",
		"Do you prefer coffee or tea",
		"I found this cool gadget online!",
		"Do you like to cook",
		"Have you ever been to Paris",
		"I just got a new bike!",
		"What's your favorite ice cream flavor",
		"Do you follow any sports",
		"I love this new TV show!",
		"Have you tried this new restaurant",
		"What kind of music do you like",
		"Do you have a favorite artist",
		"I'm planning a road trip!",
		"What's your dream job",
		"Do you enjoy reading",
		"I just adopted a puppy!",
		"Have you seen this amazing sunset",
		"What's your favorite type of weather",
		"Do you play any video games",
		"I started learning a new language!",
		"Have you ever gone skydiving",
		"What's your favorite season",
		"Do you like to go hiking",
		"I just finished a great book!",
		"What's your favorite movie",
		"Do you	 enjoy photography",
		"I found a great podcast!",
		"What's your favorite dessert",
		"Do you collect anything",
		"I'm thinking about getting a tattoo!",
		"What's your favorite holiday",
		"Do you like to draw or paint",
		"I'm really into fitness lately!",
		"What's your favorite color",
		"Do you have a green thumb",
		"I love your new haircut!",
		"Have you ever been on a cruise",
		"What's your favorite type of food",
		"Do you enjoy camping",
		"I'm planning to redecorate my room!",
		"I love discovering new music",
		"Have you ever tried a new sport",
		"It's amazing how nature can be so calming",
		"I enjoy experimenting with new recipes",
		"Do you like to read before bed",
		"Traveling can open your eyes to new cultures",
		"I've always wanted to learn a new language",
		"Gardening is such a relaxing hobby",
		"Do you enjoy a good mystery novel",
		"Coffee shops are great for people watching",
		"Exploring different cuisines is so much fun",
		"Do you have a favorite artist",
		"Spending time outdoors can be really refreshing",
		"A good book can transport you to another world",
		"Do you prefer a cozy night in or a night out",
		"I find history to be fascinating",
		"What's your favorite way to unwind",
		"I love attending live concerts",
		"Trying new foods is always exciting",
		"Do you have a favorite hobby",
		"Baking can be a fun and rewarding experience",
		"I enjoy visiting museums and art galleries",
		"Spending time with friends is always enjoyable",
		"A long walk in the park can be so peaceful",
		"Do you like to write in your free time",
		"Exploring nature trails can be a great adventure",
		"A warm cup of tea is perfect for relaxing",
		"I love discovering new coffee blends",
		"Learning about different cultures is enriching",
		"What's your favorite way to exercise",
		"I find puzzles to be quite challenging",
		"Listening to podcasts can be really interesting",
		"Do you enjoy playing board games",
		"A good movie night is always fun",
		"Trying out new technology can be exciting",
		"What's your favorite type of weather",
		"I love attending local festivals",
		"Do you enjoy DIY crafts",
		"A day at the beach can be so rejuvenating",
		"I find meditation to be very calming",
		"Exploring new neighborhoods can be fun",
		"Do you have a favorite TV show",
		"I enjoy watching documentaries",
		"A cozy blanket is perfect for a chilly evening",
		"Trying new workout routines can be motivating",
		"Do you like to visit farmer's markets",
		"I love the feeling of accomplishment after a workout",
		"Spending a day with family is always special",
		"I find painting to be a great creative outlet",
		"A good book can make a rainy day enjoyable",
		"Do you enjoy visiting historical sites",
		"I love spending time in nature",
		"Trying out new recipes can be a fun challenge",
		"A day of relaxation can be just what you need",
		"Do you have a favorite place to shop",
		"Exploring different cuisines can be a culinary adventure",
		"I enjoy listening to live music",
		"A beautiful sunset can be so inspiring",
		"Do you like to plan your trips in advance",
		"I find yoga to be very beneficial",
		"Spending time in the garden is very fulfilling",
		"Do you enjoy attending sporting events",
		"A good cup of coffee can start your day right",
		"I love going to art shows",
		"Exploring new hobbies can be exciting",
		"Do you enjoy visiting new cities",
		"I find that taking long walks helps clear my mind",
		"Trying out new technologies can be fascinating",
		"Do you like to collect anything",
		"A good night's sleep can make all the difference",
		"I love learning new skills",
		"Spending time with pets can be very comforting",
		"Do you enjoy going to the theater",
		"A relaxing bath is perfect after a long day",
		"I enjoy reading about personal development",
		"Trying new restaurants can be an adventure",
		"Do you like to watch cooking shows",
		"I find hiking to be very invigorating",
		"Spending time at the beach can be so refreshing",
		"Do you enjoy crafting and creating things",
		"A good workout always makes me feel better",
		"I love exploring different music genres",
		"Trying out new fashion styles can be fun",
		"Do you enjoy visiting zoos or aquariums",
		"A cozy sweater is perfect for a chilly day",
		"I find learning about science to be fascinating",
		"Spending time with loved ones is always rewarding",
		"Do you like to explore new technology gadgets",
		"I love going on spontaneous road trips",
		"A day spent outdoors can be very fulfilling",
		"Do you enjoy watching educational videos",
		"I find it relaxing to listen to nature sounds",
		"Trying new hobbies can be a great way to learn",
		"Spending time on a creative project can be satisfying",
		"Do you like to attend workshops or classes",
		"I love	 discovering new places to visit",
		"A nice cup of hot cocoa is perfect for winter",
		"Do you enjoy watching live theater performances",
		"I find that journaling helps me stay organized",
		"Spending time exploring new ideas is always inspiring",
		"Have you seen this new movie", 
		"Do you like hiking", 
		"I'm thinking of trying yoga.", 
		"What's your favorite food", 
		"Have you ever been to Japan", 
		"I can't stop listening to this podcast!", 
		"Do you like to travel", 
		"Are you a cat person or a dog person", 
		"What's your favorite book", 
		"Do you have a hobby", 
		"Have you ever gone skydiving", 
		"What's your favorite TV show", 
		"Do you play any instruments", 
		"Have you been to the new cafe", 
		"What's your dream job", 
		"Do you believe in fate", 
		"Have you heard the latest news", 
		"What's your favorite way to relax", 
		"Do you cook at home", 
		"Have you ever tried painting", 
		"Do you like board games", 
		"Are you more of a morning or night person", 
		"Do you like spicy food", 
		"What's your favorite holiday", 
		"Have you ever gone camping", 
		"What's your favorite song right now", 
		"Do you watch documentaries", 
		"Are you into any sports", 
		"Do you like gardening", 
		"What's your favorite type of dessert", 
		"Do you drink coffee or tea", 
		"Have you ever been to a concert", 
		"Do you like sushi", 
		"Are you into fashion", 
		"What's your favorite ice cream flavor", 
		"Do you read the news daily", 
		"Are you a fan of mystery novels", 
		"Have you ever tried rock climbing", 
		"What's your favorite animal", 
		"Do you like photography", 
		"What's your favorite kind of weather", 
		"Have you tried meditating", 
		"What's your favorite color", 
		"Do you like swimming", 
		"Have you ever been to a music festival", 
		"What's your favorite way to spend a weekend", 
		"Do you like roller coasters", 
		"What's your go-to karaoke song", 
		"Have you ever learned a new language", 
		"Do you like video games", 
		"What's your favorite app", 
		"Do you prefer beaches or mountains", 
		"Have you tried this recipe", 
		"Do you collect anything", 
		"What's your favorite pizza topping", 
		"Do you like working out", 
		"Are you into podcasts", 
		"What's your favorite season", 
		"Have you ever met a celebrity", 
		"Do you like reading poetry", 
		"Have you been to an amusement park recently", 
		"Do you enjoy baking", 
		"What's your favorite superhero", 
		"Do you like shopping", 
		"What's the last movie you saw", 
		"Have you ever gone fishing", 
		"What's your dream vacation", 
		"Do you like karaoke", 
		"Have you been to a wedding recently", 
		"What's your favorite fruit", 
		"Do you prefer texting or calling", 
		"Do you enjoy puzzles", 
		"What's your favorite hobby", 
		"Have you ever been scuba diving", 
		"Do you like stargazing", 
		"What's your favorite social media platform", 
		"Have you ever tried photography", 
		"Do you enjoy wine tasting", 
		"What's your favorite sport to watch", 
		"Have you ever tried yoga", 
		"What's your favorite childhood memory", 
		"Do you like hot or cold weather", 
		"Have you ever tried martial arts", 
		"What's your favorite type of cake", 
		"Do you prefer reading or watching TV", 
		"Have you ever been to a zoo", 
		"What's your favorite outdoor activity", 
		"Do you like attending live shows", 
		"What's your favorite sandwich", 
		"Have you ever written a journal", 
		"Do you like playing card games", 
		"What's your favorite flower", 
		"Do you enjoy hiking", 
		"Have you ever been to a museum", 
		"Do you enjoy road trips", 
		"What's your favorite breakfast food", 
		"Have you ever gone bird watching", 
		"Do you like to dance", 
		"What's your favorite scent", 
		"Have you ever been to a spa", 
		"Do you enjoy camping", 
		"What's your favorite restaurant", 
		"Have you ever been to the theater", 
		"Do you like working with your hands", 
		"What's your favorite podcast episode", 
		"Have you ever tried pottery", 
		"What's your favorite way to stay active", 
		"Do you like watching the sunrise", 
		"What's your favorite comic book", 
		"Have you ever been to an art gallery", 
		"What's your favorite thing to do on a lazy day", 
		"Do you enjoy crafting", 
		"What's your favorite city", 
		"Have you ever ridden a horse", 
		"What's your favorite genre of music", 
		"Do you like trying new foods", 
		"What's your favorite place to visit", 
		"Have you ever tried knitting", 
		"What's your favorite board game", 
		"Do you enjoy going to the beach", 
		"What's your favorite sport to play", 
		"Have you ever gone whale watching", 
		"Do you like outdoor barbecues", 
		"What's your favorite fast food", 
		"Have you ever been to a haunted house", 
		"Do you like to draw", 
		"What's your favorite type of movie", 
		"Have you ever tried sewing", 
		"What's your favorite vacation spot", 
		"Do you enjoy ice skating", 
		"What's your favorite workout routine", 
		"Have you ever been on a boat", 
		"Do you enjoy skiing or snowboarding", 
		"What's your favorite time of day", 
		"Have you ever gone snorkeling", 
		"What's your favorite thing to cook", 
		"Do you enjoy playing sports", 
		"What's your favorite thing to do with friends", 
		"Have you ever tried a new hobby recently", 
		"Do you like playing chess", 
		"What's your favorite food to order in", 
		"Have you ever been on a train ride", 
		"Do you like to volunteer", 
		"What's your favorite place to relax", 
		"Have you ever gone zip-lining", 
		"Do you like theme parks", 
		"What's your favorite holiday tradition", 
		"Have you ever been to a farm", 
		"What's your favorite snack", 
		"Do you enjoy fishing", 
		"What's your favorite thing to collect", 
		"Have you ever gone on a cruise", 
		"Do you like attending concerts", 
		"What's your favorite comedy show", 
		"Have you ever tried making sushi", 
		"Do you enjoy running", 
		"What's your favorite subject in school", 
		"Have you ever been on a road trip", 
		"What's your favorite TV series right now", 
		"Do you like playing video games", 
		"What's your favorite ice cream topping", 
		"Have you ever been to a magic show", 
		"Do you like playing tennis", 
		"What's your favorite childhood TV show", 
		"Have you ever tried vegan food", 
		"Do you like visiting parks", 
		"What's your favorite vegetable", 
		"Have you ever tried mountain biking", 
		"Do you like attending festivals", 
		"What's your favorite animal", 
		"Have you ever gone to a zoo", 
		"What's your favorite hobby for relaxing", 
		"Do you like playing with pets", 
		"What's your favorite musical instrument", 
		"Have you ever visited a castle", 
		"Do you enjoy drinking smoothies", 
		"What's your favorite road trip destination", 
		"Have you ever been to a fair", 
		"What's your favorite time of the year", 
		"Do you like collecting art", 
		"What's your favorite kind of cake", 
		"Have you ever been in a play", 
		"Do you like decorating for holidays", 
		"What's your favorite kind of pie", 
		"Have you ever tried gourmet cooking", 
		"Do you like listening to audiobooks", 
		"What's your favorite type of candy", 
		"Have you ever visited a botanical garden", 
		"Do you like staying in or going out", 
		"What's your favorite DIY project", 
		"Have you ever been on a sailboat", 
		"Do you enjoy trying new recipes", 
		"What's your favorite family tradition", 
		"Have you ever attended a cooking class", 
		"Do you like listening to vinyl records", 
		"What's your favorite food truck", 
		"Have you ever been on a hot air balloon ride", 
		"Do you like organizing things", 
		"What's your favorite online store", 
		"Have you ever participated in a marathon", 
		"Do you enjoy going to art galleries", 
		"What's your favorite way to unwind", 
		"Have you ever visited a lighthouse", 
		"Do you like attending sports events"
]
	
# The headers needed to send a message
headers = {
    "Authorization": TOKEN,
    "Content-Type": "application/json"
}

# The API URL for sending messages
url = f"https://discord.com/api/v9/channels/{CHANNEL_ID}/messages"

while True:
    # Pick a random message from the list
    message = random.choice(MESSAGES)

    # The data to send in the request
    data = {
        "content": message
    }

    # Sending the message
    response = requests.post(url, headers=headers, json=data)
    if response.status_code == 200:
        print(f"Message sent successfully: {message}")
    else:
        print(f"Failed to send message. Status code: {response.status_code}")

    # Wait for 1 second
    time.sleep(random.uniform(1, 5))
